/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1e26e2727adbff35127a9c3e3e878664)
interface __BaseEnv_Env {
	KV: KVNamespace;
	RESUME_FILES: R2Bucket;
	JOB_FEEDS: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	RESUME_QUEUE: Queue;
	RESUME_DLQ: Queue;
	ASSETS: Fetcher;
	RESUME_STUDIO_ENABLED: "true";
	RESUME_DAILY_MATCHING_ENABLED: "true";
	RESUME_AUTO_BUILD_ENABLED: "false";
	RESUME_EMAIL_DIGESTS_ENABLED: "true";
	CREDIT_ENFORCEMENT_ENABLED: "true";
	BETA_APPLICATION_PACK_CREDITS: "1";
	RESUME_ROLLOUT_PERCENT: "0";
	RESUME_DAILY_BUILD_LIMIT: "25";
	RESUME_DAILY_AI_BUDGET_USD: "5";
	RESUME_MODEL: "gpt-5.6-sol";
	REQUIRE_AI_GATEWAY: "true";
	RESUME_EMAIL_FROM: "updates@livejobindex.com";
	PRIVACY_POLICY_VERSION: "2026-07-22";
	ANALYTICS_RETENTION_DAYS: "90";
	SCAN_COORDINATOR: DurableObjectNamespace<import("./src/worker").ScanCoordinator>;
	USER_COORDINATOR: DurableObjectNamespace<import("./src/worker").UserMutationCoordinator>;
	RATE_LIMITER: DurableObjectNamespace<import("./src/worker").RateLimitCoordinator>;
	RESUME_WORKFLOW: Workflow /* ResumeBuildWorkflow from job-tracker-resume-workflow */;
	ACCOUNT_WORKFLOW: Workflow /* AccountLifecycleWorkflow from job-tracker-resume-workflow */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "ScanCoordinator" | "UserMutationCoordinator" | "RateLimitCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESUME_STUDIO_ENABLED" | "RESUME_DAILY_MATCHING_ENABLED" | "RESUME_AUTO_BUILD_ENABLED" | "RESUME_EMAIL_DIGESTS_ENABLED" | "CREDIT_ENFORCEMENT_ENABLED" | "BETA_APPLICATION_PACK_CREDITS" | "RESUME_ROLLOUT_PERCENT" | "RESUME_DAILY_BUILD_LIMIT" | "RESUME_DAILY_AI_BUDGET_USD" | "RESUME_MODEL" | "REQUIRE_AI_GATEWAY" | "RESUME_EMAIL_FROM" | "PRIVACY_POLICY_VERSION" | "ANALYTICS_RETENTION_DAYS">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}