name = "job-tracker"
main = "src/worker.js"
compatibility_date = "2025-04-01"
workers_dev = true

[[kv_namespaces]]
binding = "KV"
id = "8cf95c7c04054745bff09d88ea57d707"

[triggers]
crons = ["0 3 * * *"]

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability]
enabled = true

[[routes]]
pattern = "resumeforjd.com"
custom_domain = true
zone_id = "26201f140ccd499dca6a53206fe8e253"

[[routes]]
pattern = "www.resumeforjd.com"
custom_domain = true
zone_id = "26201f140ccd499dca6a53206fe8e253"
