alter table public.user_jobs
  add column if not exists viewed_at timestamptz;

alter table public.users
  alter column brand_theme set default 'graphite';

create table if not exists public.user_job_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  job_id text not null,
  event_type text not null check (
    event_type in (
      'viewed',
      'status_changed',
      'starred',
      'note_added'
    )
  ),
  from_status text,
  to_status text,
  created_at timestamptz not null default now()
);

create index if not exists user_jobs_user_id_viewed_at_idx
  on public.user_jobs (user_id, viewed_at desc)
  where viewed_at is not null;

create index if not exists user_job_history_user_job_created_at_idx
  on public.user_job_history (user_id, job_id, created_at desc);

create table if not exists public.job_postings (
  id text primary key,
  source text not null,
  source_token text,
  company text not null,
  title text not null,
  url text not null,
  first_seen_date date,
  last_seen_date date,
  last_filled_date date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.job_snapshots (
  id bigint generated by default as identity primary key,
  job_id text not null references public.job_postings(id) on delete cascade,
  scan_date date not null,
  title text not null,
  location text,
  city text,
  country text,
  role_family text,
  seniority text,
  visa text,
  score integer,
  tier text,
  is_new boolean not null default false,
  is_filled boolean not null default false,
  created_at timestamptz not null default now(),
  unique (job_id, scan_date)
);

create table if not exists public.daily_scan_stats (
  scan_date date primary key,
  total_jobs integer not null default 0,
  new_jobs integer not null default 0,
  filled_jobs integer not null default 0,
  per_source jsonb not null default '{}'::jsonb,
  per_country jsonb not null default '{}'::jsonb,
  per_family jsonb not null default '{}'::jsonb,
  per_tier jsonb not null default '{}'::jsonb,
  ok_count integer not null default 0,
  fail_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.anonymous_sessions (
  id uuid primary key default gen_random_uuid(),
  session_token text not null unique,
  ip_hash text,
  user_agent_fingerprint text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.job_views (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  session_id text,
  job_id text not null,
  source text not null default 'direct',
  viewed_at timestamptz not null default now()
);

create table if not exists public.search_queries (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  session_id text,
  query_text text,
  filters jsonb not null default '{}'::jsonb,
  result_count integer,
  created_at timestamptz not null default now()
);

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  session_id text,
  page_path text not null default '/',
  referrer text,
  created_at timestamptz not null default now()
);

create index if not exists job_postings_company_active_idx
  on public.job_postings (company, is_active);

create index if not exists job_snapshots_scan_date_idx
  on public.job_snapshots (scan_date desc);

create index if not exists job_snapshots_country_family_idx
  on public.job_snapshots (country, role_family);

create index if not exists job_views_viewed_at_idx
  on public.job_views (viewed_at desc);

create index if not exists job_views_job_id_viewed_at_idx
  on public.job_views (job_id, viewed_at desc);

create index if not exists search_queries_created_at_idx
  on public.search_queries (created_at desc);

create index if not exists page_views_created_at_idx
  on public.page_views (created_at desc);

drop trigger if exists job_postings_set_updated_at on public.job_postings;

create trigger job_postings_set_updated_at
before update on public.job_postings
for each row execute function public.set_updated_at();

drop trigger if exists daily_scan_stats_set_updated_at on public.daily_scan_stats;

create trigger daily_scan_stats_set_updated_at
before update on public.daily_scan_stats
for each row execute function public.set_updated_at();

alter table public.user_job_history enable row level security;
alter table public.job_postings enable row level security;
alter table public.job_snapshots enable row level security;
alter table public.daily_scan_stats enable row level security;
alter table public.anonymous_sessions enable row level security;
alter table public.job_views enable row level security;
alter table public.search_queries enable row level security;
alter table public.page_views enable row level security;

drop policy if exists "users can select own job history" on public.user_job_history;

create policy "users can select own job history"
on public.user_job_history for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "users can insert own job history" on public.user_job_history;

create policy "users can insert own job history"
on public.user_job_history for insert
to authenticated
with check ((select auth.uid()) = user_id);

grant usage on schema public to authenticated, service_role;
grant select, insert on public.user_job_history to authenticated;
grant all on public.job_postings to service_role;
grant all on public.job_snapshots to service_role;
grant all on public.daily_scan_stats to service_role;
grant all on public.anonymous_sessions to service_role;
grant all on public.job_views to service_role;
grant all on public.search_queries to service_role;
grant all on public.page_views to service_role;
grant usage, select on all sequences in schema public to service_role;
